- name: Enable UFW firewall
  ufw:
    state: enabled
    policy: "{{ ufw_default_policy }}"

- name: Allow SSH/HTTP/HTTPS in UFW
  ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ security_allowed_ports }}"

- name: Ensure fail2ban is enabled
  systemd:
    name: "{{ 'fail2ban' }}"
    enabled: yes
    state: started
