---
- name: Reload Nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Reload Apache
  ansible.builtin.systemd:
    name: apache2
    state: reloaded

- name: Reload LiteSpeed
  ansible.builtin.systemd:
    name: lshttpd
    state: restarted
